# Generated by Django 3.2 on 2021-04-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
